""" version which can be consumed from within the module """
VERSION_STR = "0.0.85"
DESCRIPTION = "pyflexebs will allow you to monitor and expand/contract you ebs in aws"
APP_NAME = "pyflexebs"
LOGGER_NAME = "pyflexebs"
