""" version which can be consumed from within the module """
VERSION_STR = "0.0.87"
DESCRIPTION = "Pyflexebs will allow you to monitor and expand/contract you EBS volumes in aws"
APP_NAME = "pyflexebs"
LOGGER_NAME = "pyflexebs"
